# Generated by Django 2.2.3 on 2019-07-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='name',
        ),
    ]
